### ISSUE TITLE
make Live chat full screen

### ISSUE THREAD

**Issue by gauravsinhaweb** [gauravsinhaweb/EduSmart#1]
![as](https://user-images.githubusercontent.com/75125943/135578805-3f490b20-ca09-4e20-b1f4-93a76fb1cda8.PNG)

**Comment by Neniya** [comment]
Can I work on it ?

**Comment by gauravsinhaweb** [comment]
@Neniya  Yes, you can

**Comment by Neniya** [comment]
Hi @gauravsinhaweb , thank you for your feedback!
Could you please explain more detail, how it should look like:
Should there be any space around chat box?

For example in the bottom there is an element:
<img width="909" alt="Screenshot 2021-10-02 at 12 21 50" src="https://user-images.githubusercontent.com/65239393/135712568-62415700-710d-43ab-8755-7c9eff26d7c9.png">

So should chat position be like here: 
<img width="916" alt="Screenshot 2021-10-02 at 12 21 16" src="https://user-images.githubusercontent.com/65239393/135712620-80ac074c-1735-48c5-bb98-2ca3e74b40d8.png">

or like here(without any space):
<img width="916" alt="Screenshot 2021-10-02 at 12 20 40" src="https://user-images.githubusercontent.com/65239393/135712629-0d222ff0-ff0d-4282-b52a-4c88a4bcbb71.png">

and what about other borders/spaces(top, left, right)?

**Comment by gauravsinhaweb** [comment]
Hi @Neniya, Thanks for replying to me back!

It should look like this (I've attached a pic). I think there are some bugs in the code which doesn't give flexibility to the Live chat CSS. If you want, you can change the whole code and make a new live chat feature to whatever design you want (upto you). 

![chatroom- gaurav](https://user-images.githubusercontent.com/75125943/135713347-86bd9e73-99a6-467d-babf-822cf7dd3e73.png)

**Comment by Neniya** [comment]
Thank you @gauravsinhaweb! It's more clear now. I've got it.

**Comment by Neniya** [comment]
@gauravsinhaweb now live chat look like this: 
<img width="1000" alt="Screenshot 2021-10-04 at 09 18 39" src="https://user-images.githubusercontent.com/65239393/135809652-5184e828-d731-4b1e-8a8e-57762c7e9279.png">

There is a Chat bot float button that I think is not on the best position in this page. What do you think?
Chat bot component exists on several pages. We can change it (move a little bit upper) for all of them, or just for this page.
If you think that it should be change only for live chat, I think it'll be better to create a new ticket( I can take it on me).

**Comment by gauravsinhaweb** [comment]
@Neniya, I appreciate your hard work, you made it exactly the same as what I designed 🤯💯. 

I think there is no actual need for a chatbot float button while chatting (in Live chat). If it is possible you can remove it (only from the Chatroom page) or you can position it  (move a little bit upper - just for this page). 

Do whatever best suits this page in terms of UI/UX, The decision is yours.

**Comment by gauravsinhaweb** [comment]
Hi @Neniya, Can you PR again, I am getting some errors in deployment.
