### ISSUE TITLE
Enhancement Sidebar

### ISSUE THREAD

**Issue by piyush-mahajan** [gauravsinhaweb/EduSmart#105]
So SideBar present on the site is very off-putting to the current UI and it looks very inconsistent with the color theme of the site,as the UIUX designer I can fix it, can you assign this task to me?

**Describe the solution you'd like**
I want to make a better UI design and a more Visually applicative design for the Sidebar and many more

**Comment by gauravsinhaweb** [comment]
> So SideBar present on the site is very off-putting to the current UI and it looks very inconsistent with the color theme of the site,as the UIUX designer I can fix it, can you assign this task to me?
> 
> **Describe the solution you'd like** I want to make a better UI design and a more Visually applicative design for the Sidebar and many more

Assigned, do share the reference link for UI/UX for sidebar

**Comment by piyush-mahajan** [comment]
ya sure
