### ISSUE TITLE
Improve coding and styling in Faq.js pages

### ISSUE THREAD

**Issue by rhnas110** [gauravsinhaweb/EduSmart#109]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/gauravsinhaweb/EduSmart/assets/51848196/020b837c-5fdf-41df-9dfd-5af12a59bfe5)
![image](https://github.com/gauravsinhaweb/EduSmart/assets/51848196/038c202e-fd18-42ab-9271-b692a702819e)
There is redundant code in first image, and inconsistent style in second image, when you open the Faq, the Faq title should turn blue like the first one.

**Describe the solution you'd like**
For the first picture about redundant code, it should use looping so that there is no redundant, and for the second picture, when Faq is opened, the Faq title style should also turn blue like the first Faq title.

**Describe alternatives you've considered**
To reduce redundant code and to maintain a consistent style.

**Additional context**
Can you take my advice and assign this task to me Sir @gauravsinhaweb ? and I am new to open source contributions and I would love to contribute to your project! I also participated in Hacktoberfest2023.

**Comment by gauravsinhaweb** [comment]
@rhnas110 thanks for pointing it out, assigned under hactoberfest
