### ISSUE TITLE
Add highlighted icon to the navigation bar

### ISSUE THREAD

**Issue by kevinzzzhu** [gauravsinhaweb/EduSmart#119]
**Is your feature request related to a problem? Please describe.**
Currently, when navigating through the application, there's no clear visual indication of which page or section the user is currently on within the navigation bar. This can lead to a less intuitive user experience, as users might feel lost or unsure about their current location within the app.

**Describe the solution you'd like**
I'd like to see the icon corresponding to the current page or section highlighted in the navigation bar. This could be achieved by changing the color that clearly indicates the active page. This will provide users with a clear understanding of their current position within the application and enhance the overall user experience.

**Describe alternatives you've considered**
An alternative could be to use text labels next to the icons or a tooltip that appears on hover, indicating the name of the page. However, a highlighted icon is a more immediate and visually appealing solution.

**Additional context**
Having clear navigation cues is essential for ensuring a smooth user experience, especially in applications with multiple sections or pages. Implementing this feature will make the navigation more user-friendly and intuitive. Can you assign this to me, I really hope to contribute to this project. @gauravsinhaweb 

Desired outcome: 
<img width="372" alt="1" src="https://github.com/gauravsinhaweb/EduSmart/assets/112826656/f7120049-0569-4be7-97b5-a47b58a3dc83">
<img width="543" alt="2" src="https://github.com/gauravsinhaweb/EduSmart/assets/112826656/d6ad9acd-3e83-442b-98f1-6c1b50b3d51c">

**Comment by gauravsinhaweb** [comment]
Assigned

**Comment by kevinzzzhu** [comment]
Hi, what color do you think will be better for the icon in this case? I am currently using gold #FFD700 at the moment.
