### ISSUE TITLE
Align Navigation Sidebar Elements for Proper Layout

### ISSUE THREAD

**Issue by P0Saurabh** [gauravsinhaweb/EduSmart#121]
![Screenshot 2023-10-20 202036](https://github.com/gauravsinhaweb/EduSmart/assets/111894219/8f70ab9b-ce98-4d40-a4c4-d0ff1cf4030a)
 Elements within the sidebar, such as menu items and icons, need to be properly aligned to enhance visual consistency and streamline navigation

**Comment by P0Saurabh** [comment]
can you assign this task to me

**Comment by gauravsinhaweb** [comment]
Assigned
