### ISSUE TITLE
Fix classroom title alignment

### ISSUE THREAD

**Issue by kevinzzzhu** [gauravsinhaweb/EduSmart#124]
The title alignments at the top {Medical, AeroSpace, Planets} are different in classrooms, they should be in the same place.

<img width="1292" alt="Screenshot 2023-10-21 at 7 45 14 pm" src="https://github.com/gauravsinhaweb/EduSmart/assets/112826656/a3dcf9ca-defc-4988-9a3b-9cc57814c93f">
<img width="1218" alt="Screenshot 2023-10-21 at 7 45 19 pm" src="https://github.com/gauravsinhaweb/EduSmart/assets/112826656/6b003ba0-63e8-45c3-8006-abd6005323ea">
<img width="1141" alt="Screenshot 2023-10-21 at 7 45 29 pm" src="https://github.com/gauravsinhaweb/EduSmart/assets/112826656/d7b75e34-1b0d-4106-aea9-7cb9042f6afd">

Can assign this to me? @gauravsinhaweb

**Comment by gauravsinhaweb** [comment]
Assigned
