### ISSUE TITLE
API Keys and sensitive information leaked in login.js

### ISSUE THREAD

**Issue by akgupta0777** [gauravsinhaweb/EduSmart#15]

**Comment by akgupta0777** [comment]
In client/pages/login.js API Keys are hardcoded and can be seen by anyone.
This can lead to billing from your API provider. API keys are something that needs to be protected in an environmental file called .env

**Comment by akgupta0777** [comment]
You have two solutions to the problem :
1) rebase your repo and store secret keys in .env files
2) create a new repo with the same code and with the .env file.

**Comment by gauravsinhaweb** [comment]
Hi @akgupta0777,  True that Thanks for letting me know, I will work on it.

**Comment by m1ga** [comment]
still: why a login at all :smile: Or use it just for the chat if you want to use the username there

**Comment by gauravsinhaweb** [comment]
> ok I see. Then at least add some information on the start/login page for those users to know what the page is about. Just seeing a "Email id" field gives no glue what your project is all about.

True, I'll remove the login page for now.. so that people  will get to know about the website. 🙌
