### ISSUE TITLE
Add a FAQs section in the webpage

### ISSUE THREAD

**Issue by TishaJhabak1014** [gauravsinhaweb/EduSmart#20]
This issue will let the necessary FQAs section created on the web page.

**Comment by TishaJhabak1014** [comment]
@gauravsinhaweb created the issue. Plz assign me. Thank you.

**Comment by gauravsinhaweb** [comment]
@TishaJhabak1014 Sure

**Comment by TishaJhabak1014** [comment]
@gauravsinhaweb Hey, being a beginner in JS and frameworks, am having a hard time navigating through the repo. and contribute. Thank you for the assignment but you may consider assigning this to a more suitable one.

**Comment by gauravsinhaweb** [comment]
> @gauravsinhaweb Hey, being a beginner in JS and frameworks, am having a hard time navigating through the repo. and contribute. Thank you for the assignment but you may consider assigning this to a more suitable one. 

Hi@TishaJhabak1014 , I am a beginner too, but if you want then I can help you making PR and navigating through the repo (maybe we can connect on discord), still you don't want to contribute. It's okay. Feel free to contribute anytime you want. :)

**Comment by TishaJhabak1014** [comment]
> > @gauravsinhaweb Hey, being a beginner in JS and frameworks, am having a hard time navigating through the repo. and contribute. Thank you for the assignment but you may consider assigning this to a more suitable one. 
> 
> Hi@TishaJhabak1014 , I am a beginner too, but if you want then I can help you making PR and navigating through the repo (maybe we can connect on discord), still you don't want to contribute. It's okay. Feel free to contribute anytime you want. :)

That will be great if you can find sometime to guide me. Will be sharing my discord id with you soon. Thank you.

**Comment by gauravsinhaweb** [comment]
> > > @gauravsinhaweb Hey, being a beginner in JS and frameworks, am having a hard time navigating through the repo. and contribute. Thank you for the assignment but you may consider assigning this to a more suitable one. 
> > 
> > Hi@TishaJhabak1014 , I am a beginner too, but if you want then I can help you making PR and navigating through the repo (maybe we can connect on discord), still you don't want to contribute. It's okay. Feel free to contribute anytime you want. :)
> 
> That will be great if you can find sometime to guide me. Will be sharing my discord id with you soon. Thank you.

No problem. My discord ID:    ! sinhagaurav#2642

**Comment by TD-17** [comment]
@gauravsinhaweb ! Is there anyone working on this issue? If not then will you please assign this issue to me ??

**Comment by gauravsinhaweb** [comment]
Hi @TD-17 ,  You can work on this issue 👍

**Comment by TD-17** [comment]
> Hi @TD-17 , You can work on this issue 👍

Okay

**Comment by TD-17** [comment]
@gauravsinhaweb ! What information should be added to fAQ page ?

**Comment by TishaJhabak1014** [comment]
> @gauravsinhaweb ! What information should be added to fAQ page ?

It's pretty much like answering questions  about the website, what it is all about?
How one can register or may be navigate hard parts, sort of. Refering to contact info while receiving feedbacks, just enhancing Ux exp.
Also, ig there video on this web app, check that out.

**Comment by Divya871** [comment]
Anyone contributing to this issue,if not I would like to go ahead.

**Comment by gauravsinhaweb** [comment]
> Anyone contributing to this issue,if not I would like to go ahead.

There is one Assignee working on this issue, still you can work in this issue, let me know if you're interested?
