### ISSUE TITLE
Clean the imports

### ISSUE THREAD

**Issue by dddqwerty** [gauravsinhaweb/EduSmart#27]
I think we need to clean the imports. And structure code also format.

**Comment by dddqwerty** [comment]
@gauravsinhaweb what do you think?

**Comment by gauravsinhaweb** [comment]
Hey @dddqwerty , yes we need to change some code structure to make the site performance better and make repo easy to read. Let me know if you're interested to do so.

**Comment by dddqwerty** [comment]
Yeap. I am interested in this. Can u assign it to me as labeled hacktober?

**Comment by dddqwerty** [comment]
I just send PR. I think you should also add label "hacktoberfest-accepted".

**Comment by gauravsinhaweb** [comment]
I'll surely add "hacktoberfest-accepted" label while merging your pull request. No need to worry about it. :)

**Comment by dddqwerty** [comment]
Thanks bro. Good luck!.
