### ISSUE TITLE
Contents are overflowing the div in the landing page

### ISSUE THREAD

**Issue by Vishnurr2k01** [gauravsinhaweb/EduSmart#28]
**Describe the bug**
The contents in the div are overflowing after entering the email and waiting for otp

**Additional context**
![1](https://user-images.githubusercontent.com/72376269/135757489-7991bcda-0bf2-4e96-a123-530058c70137.png)

Shall I fix it?

**Comment by tanmayVaish** [comment]
Assign it to me, I can look into it!

**Comment by prady8339** [comment]
hey @tanmayVaish you can fork this repo and work on it then you can propose changes by creating a pull if the problem is  fixed , hope that helps.

**Comment by Vishnurr2k01** [comment]
> hey @tanmayVaish you can fork this repo and work on it then you can propose changes by creating a pull if the problem is fixed , hope that helps.

**Comment by gauravsinhaweb** [comment]
Hi @prady8339 , Thank you for assisting him 😀
