### ISSUE TITLE
Add pull request template 

### ISSUE THREAD

**Issue by SrishtiArya07** [gauravsinhaweb/EduSmart#41]
**Is your feature request related to a problem? Please describe.**
This repo does not contain a Pull Request template.

**Describe the solution you'd like**
I would like to add a Pull request template so that if someone wants to raise a pr they can select the right template and contribute.

**Describe alternatives you've considered**
NA

**Additional context**
I want to contribute to this repo for Hactoberfest21. Kindly assign this issue to me!

**Comment by SrishtiArya07** [comment]
@gauravsinhaweb check out this issue, please.

**Comment by gauravsinhaweb** [comment]
> @gauravsinhaweb can I work on this issue?

@SrishtiArya07 Yes, go for it 👍

**Comment by SrishtiArya07** [comment]
@gauravsinhaweb Please check out the pr #42  I raised for this issue. Tell me if you need any changes.
