### ISSUE TITLE
Add ESLint, Prettier and EditorConfig in clientside

### ISSUE THREAD

**Issue by girordo** [gauravsinhaweb/EduSmart#49]
**Is your feature request related to a problem? Please describe.**
Not a problem but it could be in the future. Adding ESLint, Prettier and EditorConfig we could maintain effectively, granting a code pattern as the project scalate.

**Describe the solution you'd like**
Add ESLint, Prettier and EditorConfig dependencies and configuring all of them.

**Describe alternatives you've considered**
I don't know any alternatives for code formatting.

**Additional context**
I don't know any additional contexts

**Comment by gauravsinhaweb** [comment]
Hi @girordo , Let me know if you're interested in this issue.

**Comment by girordo** [comment]
> Hi @girordo , Let me know if you're interested in this issue.

Yes, I'am 😄

**Comment by gauravsinhaweb** [comment]
> > Hi @girordo , Let me know if you're interested in this issue.
> 
> Yes, I'am 😄

Great! Go for it 👍
